Разбивка на модули и доработка фукнции генерации массива объекта
htmlacademy-javascript/465875-kekstagram-23 pull request #4
Opened 2021-06-14 14:45 UTC by kalaganov5

2021-06-14 18:48 UTC, ademaro commented on js/mock/demo-data.js
> +const photoDescriptions = new Array(NUMBER_PHOTO_DESCRIPTIONS).fill(null).map(createPicturesDescription);
Ты создаёшь данные и их экспортируешь, а надо сделать ф-цию генерации данных и её экспрортировать. Генерировать непостредственно данные надо уже будет в main.js

Это принципиальный момент, поэтому жду небольшую поправку и закроем ПР

2021-06-14 18:49 UTC, ademaro commented on js/mock/utils.js
> +
вот в этом модуле логичнее держать вспомогательные ф-ции для моков, например, getRandomNumber

2021-06-14 18:50 UTC, ademaro requested changes
Жду небольшую поправку и двинем дальше

2021-06-14 19:16 UTC, kalaganov5 commented on js/mock/utils.js
> +
Принято, думал что функция `getRandomNumber` может понадобиться в будущем

2021-06-15 21:42 UTC, ademaro commented on js/main.js
> +createPhotoDescriptions(NUMBER_PHOTO_DESCRIPTIONS);
👍🏼

2021-06-15 21:43 UTC, ademaro approved these changes
отлично!

2021-06-15 21:43 UTC, merged